pipeline {
  agent {
    any
  }
  stages {
    stage ("CI") {
      steps {
        stages {
          stage ("Build") {
            steps {
              sh '''
                echo "Build Stage"
              '''
            }
          }
          stage ("Push") {
            steps {
              sh '''
                echo "Build Stage"
              '''
            }
          }
        }
      }
    }
    stage ("CD") {
      steps {
        stages {
          stage "Deploy" {
            steps {
              sh '''
                echo "Deploy Stage"
              '''
            }
          }
        }
      }
    }
  }
}
