pipeline {
  agent any
  triggers {
    pollSCM '*/5 * * * *'
  }
  stages {
    stage ("CI") {
      stages {
        stage ("Build") {
          steps {
            withCredentials([usernamePassword(credentialsId: 'Dockerhub-Caltech', passwordVariable: 'password', usernameVariable: 'username')]) {
              sh '''
                echo "${username}"
                echo "${password}"
                echo "Pull and Build Stage"
                docker build -t ${username}/nginx-jenkins -f Dockerfile .
              '''
            }
          }
        }
        stage ("Push") {
          steps {
            withCredentials([usernamePassword(credentialsId: 'Dockerhub-Caltech', passwordVariable: 'password', usernameVariable: 'username')]) {
              sh '''
                echo "Push Stage"
                docker login -u ${username} -p ${password}
                docker push ${username}/nginx-jenkins
                docker logout
              '''
            }
          }
        }
      }
    }
    stage ("CD") {
      stages {
        stage ("Pull product image") {
          steps {
            withCredentials([usernamePassword(credentialsId: 'Dockerhub-Caltech', passwordVariable: 'password', usernameVariable: 'username')]) {
            sh '''
              echo "Pull product image stage"
              docker login -u ${username} -p ${password}
              docker pull ${username}/nginx-jenkins
              docker logout
            '''
            }
          }
        }
        stage ("Deploy") {
          steps {
            withCredentials([usernamePassword(credentialsId: 'Dockerhub-Caltech', passwordVariable: 'password', usernameVariable: 'username')]) {
            sh '''
              echo "Deploy Stage"
              docker pull ${username}/nginx-jenkins
              docker run --rm -d -p 8080:80 --name nginxcontainercaltech ${username}/nginx-jenkins
            '''
            }
          }
        }
      }
    }
  }
}
